- exp_params:
    description: Training network for RED_EYES requisite
    name: train_vgg16
    src_files:
    - exp_runner.py
    - data_processor.py
    - model_trainer.py
    - model_evaluator.py
    tags:
    - vgg16
    - ground truths
    - adamax
    - pybossa
    - binary_output
    - red_eyes
  net_train_params:
    base_model: !!python/object/apply:model_trainer.BaseModel
    - prep_function: !!python/name:tensorflow.python.keras.applications.vgg16.preprocess_input ''
      target_size: !!python/tuple
      - 224
      - 224
    batch_size: 64
    dropout: 0.3
    early_stopping: 10
    learning_rate: 0.001
    n_epochs: 15
    optimizer: !!python/object/apply:model_trainer.Optimizer
    - Adamax
    test_prop: 0.05
    train_prop: 0.9
    validation_prop: 0.05
    validation_split: 0.1
  properties:
    aligned: true
    balance_input_data: false
    gt_names:
      test: []
      train_validation: []
      train_validation_test:
      - !!python/object/apply:gt_loaders.gt_names.GTName
        - fvc
    model_name: ''
    reqs:
    - !!python/object/apply:utils.constants.ICAO_REQ
      - mouth
    sample_prop: 1.0
    sample_training_data: false
    save_trained_model: false
    train_model: true
    use_gt_data: true
  use_neptune: false
